### ISSUE TITLE
Example LSM9DS1_BASIC_SPI no pin 9 on Photon

### ISSUE THREAD

**Issue by ScruffR** [sparkfun/SparkFun_LSM9DS1_Particle_Library#1]
In your SPI sample you set this

```
If you have the Photon IMU shield, no extra wiring is required.
If you're using a breakout, the pin-out is as follows:
    LSM9DS1 --------- Photon
    CS_AG ------------- 9
    CS_M ------------- 10

///////////////////////
// Example SPI Setup //
///////////////////////
// Define the pins used for our SPI chip selects. We're
// using hardware SPI, so other signal pins are set in stone.
#define LSM9DS1_M_CS    10 // Can be any digital pin
#define LSM9DS1_AG_CS   9  // Can be any other digital pin
```

But there is no pin 9 on a Particle Core/Photon/Electron.
And Particle would encourage the use of the more expressive pin references like `A0` instead of `10`.

Could it be that the default wiring (by use of jumpers `CS A/G` would be `A1` (11) and `CS_M` would be `A2` (12))?

**Comment by jimblom** [comment]
Good catch. I pushed a fix with correct comments and pin variables set to the IMU shield pins.

Thanks!

**Comment by ScruffR** [comment]
Cool, thanks :+1: 
@jimblom, could you please also push this to the [Particle Build Web IDE](https://build.particle.io)?

**Comment by jimblom** [comment]
Yup, should be up there now.
